apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envoy
  namespace: default
data:
  envoy.yaml: >
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.envoy.containerPort }}
        use_original_dst: true
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              tracing:
                operation_name: ingress
              stat_prefix: ingress_http
              route_config:
                {{/* i think i can change this from service1_route */}}
                name: service_route
                virtual_hosts:
                - name: {{ .Values.name }}
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: local_service
                    decorator:
                      operation: {{ .Values.name }}-envoy-ingress
              http_filters:
              - name: envoy.router
                config: {}
      {{/* this listener is not used until app is changed to use service-b-envoy - so it sends to this listener (localhost:9090) */}}
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.envoy.egressPort }}
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              tracing:
                operation_name: egress
              stat_prefix: egress_http
              {{/* REVISIT: do i need to create the specific routes ahead of time????? */}}
              route_config:
                name: serviceb_route
                virtual_hosts:
                - name: service-b-envoy
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      host_rewrite: service-b
                      cluster: service_b
                    decorator:
                      operation: service_b
              http_filters:
              - name: envoy.router
                config: {}

      clusters:
      - name: local_service
        connect_timeout: 0.250s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: {{ .Values.containerPort }}
      - name: service_b
        connect_timeout: 0.250s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: service-b
            port_value: 80
{{/* 
      - name: honeycomb-opentracing-proxy
        connect_timeout: 1s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: honeycomb-opentracing-proxy
            port_value: 9411
    tracing:
      http:
        name: envoy.zipkin
        config:
          collector_cluster: honeycomb-opentracing-proxy
          collector_endpoint: "/api/v1/spans"
*/}}
    admin:
      access_log_path: "/var/log/admin-access.log"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
